apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: test
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: mobarak9239/api-server:latest
          ports:
            - containerPort: 8081