apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  namespace: prom
  name: pgpool-service-monitor
spec:
  endpoints:
    - interval: 10s
      port: pgpool-stats-port
  selector:
    matchLabels:
      app: pgpool-stats