apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: custom-postgres-1
  namespace: demo
spec:
  clientAuthMode: "cert"
  terminationPolicy: WipeOut
  version: "13.13"
  replicas: 1
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      name: pg-ca-issuer
      kind: Issuer
    certificates:
      - alias: server
        subject:
          organizations:
            - kubedb:server
        dnsNames:
          - localhost
        ipAddresses:
          - "127.0.0.1"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi