apiVersion: v1
kind: Secret
metadata:
  name: pgpool-pcp-secret
  namespace: demo
type: Opaque
data:
  username: bW9iYXJhaw==   # Base64-encoded username (e.g., "mobarak")
  password: MTIz           # Base64-encoded password (e.g., "123")
