apiVersion: kubedb.com/v1alpha2
kind: ProxySQL
metadata:
  name: proxy-server
  namespace: demo
spec:
  version: "2.3.2-debian"  
  replicas: 3
  backend:
    name: mysql-server
  podTemplate:
    spec:
      initContainers:
      - name: hello
        image: alpine
        args: ["/bin/sh", "-c", "echo hello-world"]
  terminationPolicy: WipeOut
